### ISSUE TITLE
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt5' is currently running

### ISSUE THREAD

**Issue by myildir3** [hsayama/PyCX#1]
Hi Dr. Sayama,

I am trying to run `pycxsimulator.py` for SIR model simulation using Spyder. However, I am receiving the following error:

`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt5' is currently running`

I also did this: "Note for Spyder users: Dynamic simulations may cause a conflict with Spyder's own graphics backend. In such a case, go to "Run" -> "Configuration per file" and select "Execute in an external system terminal"." But, I received the following error:

```
Traceback (most recent call last):
  File "G:\My Drive\GitHub\Other-Research-Items\PyCX\net-voter.py", line 30, in <module>
    pycxsimulator.GUI().start(func=[initialize, observe, update])
  File "G:\My Drive\GitHub\Other-Research-Items\PyCX\pycxsimulator.py", line 276, in start
    self.modelInitFunc()
  File "G:\My Drive\GitHub\Other-Research-Items\PyCX\net-voter.py", line 13, in initialize
    g.node[i]['state'] = choice(range(k))
AttributeError: 'Graph' object has no attribute 'node'

```
Could you please help me with this?

Regards,
Mehmet

**Comment by hsayama** [comment]
Thanks Mehmet. So, the "Configuration per file" worked to avoid the first issue.

For the second issue, which version of NetworkX are you using? Depending on the version, you may need to change "g.node" to "g.nodes".

**Comment by myildir3** [comment]
Thank you, Dr. Sayama. As you said  "Configuration per file" worked. I changed `g.node` to `g.nodes` since the version of NetworkX is 2.4 and the simulation run in `net-voter.py`. However, I come across other errors, such as `AttributeError: 'Graph' object has no attribute 'nodes_iter'`. Which NetworkX version is used while typing codes in GitHub? I could install the compatible version in order to reduce errors.

**Comment by hsayama** [comment]
I don't think the "nodes_iter" method was used anywhere in the most recent PyCX code. Where did you get that error?

The code was developed using NetworkX 2.3. Perhaps the method names changed when they upgraded to 2.4. If you replace "nodes_iter" with just "nodes", it should work.

**Comment by myildir3** [comment]
I got the error while running `adaptive-network-opinion-dynamics.py` and it has the function `notes_iter`. PyCX is running perfectly. Thank you, Dr. Sayama.

**Comment by hsayama** [comment]
That code is not in the most recent PyCX. Please download the most recent codes.

**Comment by myildir3** [comment]
I forked PyCX repository and using codes in this repository. Are these codes the most recent one?

**Comment by hsayama** [comment]
This one is the most recent version:
https://github.com/hsayama/PyCX

It doesn't contain adaptive-network-opinion-dynamics.py .

**Comment by myildir3** [comment]
Thank you, Dr. Sayama! My bad. I run several codes and they are perfectly running.

**Comment by hsayama** [comment]
Great! Thanks.
