### ISSUE TITLE
Screen freezes on pyxsimulator on net-networkgrowth-old.py example

### ISSUE THREAD

**Issue by Oolev** [hsayama/PyCX#3]
The application screen freezes on Ubuntu 18.04.2 LTS OS  when I run it (python 3.6.9) 
But it smoothly runs on Windows OS, I haven' tested it on Mac OS.

**Comment by hsayama** [comment]
Thanks. Could the following be helpful? I don't have Ubuntu environment, so can't check what the problem is:
https://www.pyimagesearch.com/2015/08/24/resolved-matplotlib-figures-not-showing-up-or-displaying/

**Comment by Oolev** [comment]
Hello, thanks for the link. It helped a lot, I just removed matplotlib and re-installed it, and it worked!
```
pip uninstall matplotlib
pip install matplotlib
```

**Comment by hsayama** [comment]
Great, thanks for letting me know!
